package app.bank;

import app.check.Check;
import javafx.beans.property.StringProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.SimpleLongProperty;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bank generated by hbm2java
 */
@Entity
@Table(name = "bank", catalog = "sm"
)
public class Bank implements java.io.Serializable {


    private LongProperty idBank;
    private StringProperty name;
    private StringProperty email;
    private StringProperty phone;
    private Set<Check> checks = new HashSet<Check>(0);

    public Bank() {
        this.idBank = new SimpleLongProperty();
        this.name = new SimpleStringProperty();
        this.email = new SimpleStringProperty();
        this.phone = new SimpleStringProperty();
    }

    public LongProperty idBankProperty() {
        return idBank;
    }

    public StringProperty nameProperty() {
        return name;
    }

    public StringProperty emailProperty() {
        return email;
    }

    public StringProperty phoneProperty() {
        return phone;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_bank", unique = true, nullable = false)
    public Long getIdBank() {
        return this.idBank.get();
    }

    public void setIdBank(Long idBank) {
        this.idBank.set(idBank);
    }

    @Column(name = "name")
    public String getName() {
        return this.name.get();
    }

    public void setName(String name) {
        this.name.set(name);
    }

    @Column(name = "email")
    public String getEmail() {
        return this.email.get();
    }

    public void setEmail(String email) {
        this.email.set(email);
    }

    @Column(name = "phone")
    public String getPhone() {
        return this.phone.get();
    }

    public void setPhone(String phone) {
        this.phone.set(phone);
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bank")
    public Set<Check> getChecks() {
        return this.checks;
    }

    public void setChecks(Set<Check> checks) {
        this.checks = checks;
    }

    @Override
    public String toString() {
        return getName();
    }
}
