package app.category;

import app.item.Item;
import javafx.beans.property.StringProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.SimpleLongProperty;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "sm"
)
public class Category implements java.io.Serializable {

    private LongProperty idCategory;
    private StringProperty label;
    private StringProperty description;
    private Set<Item> items = new HashSet<Item>(0);

    public Category() {
        this.idCategory = new SimpleLongProperty();
        this.label = new SimpleStringProperty();
        this.description = new SimpleStringProperty();
    }

    public LongProperty idCategoryProperty() {
        return idCategory;
    }

    public StringProperty labelProperty() {
        return label;
    }

    public StringProperty descriptionProperty() {
        return description;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_category", unique = true, nullable = false)
    public Long getIdCategory() {
        return this.idCategory.get();
    }

    public void setIdCategory(Long idCategory) {
        this.idCategory.set(idCategory);
    }

    @Column(name = "label")
    public String getLabel() {
        return this.label.get();
    }

    public void setLabel(String label) {
        this.label.set(label);
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description.get();
    }

    public void setDescription(String description) {
        this.description.set(description);
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
    public Set<Item> getItems() {
        return this.items;
    }

    public void setItems(Set<Item> items) {
        this.items = items;
    }

    @Override
    public String toString() {
        return getLabel();
    }
}
