package app.check;

import app.payment.Payment;
import app.bank.Bank;
import javafx.beans.property.ObjectProperty;
import javafx.beans.property.StringProperty;
import javafx.beans.property.SimpleObjectProperty;
import javafx.beans.property.SimpleStringProperty;
import java.time.LocalDate;

import java.sql.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Check generated by hbm2java
 */
@Entity
@Table(name = "check", catalog = "sm"
)
@PrimaryKeyJoinColumn(name="id_payment")  
public class Check extends Payment implements java.io.Serializable {

    private ObjectProperty<Bank> bank;

    private StringProperty num;
    private StringProperty name;
    private ObjectProperty<LocalDate> dueDate;
    private StringProperty note;
    //private StringProperty state;

    public Check() {
        this.bank = new SimpleObjectProperty();
        this.num = new SimpleStringProperty();
        this.name = new SimpleStringProperty();
        this.dueDate = new SimpleObjectProperty();
        this.note = new SimpleStringProperty();
        //this.state = new SimpleStringProperty();
    }


    public StringProperty numProperty() {
        return num;
    }

    public StringProperty nameProperty() {
        return name;
    }

    public StringProperty noteProperty() {
        return note;
    }

//    public StringProperty stateProperty() {
//        return state;
//    }

    public ObjectProperty<Bank> bankProperty(){
        return bank;
    }
    public ObjectProperty<LocalDate> dueDateProperty(){
        return dueDate;
    }
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_bank", nullable = false)
    public Bank getBank() {
        return this.bank.get();
    }

    public void setBank(Bank bank) {
        this.bank.set(bank);
    }


    @Column(name = "num")
    public String getNum() {
        return this.num.get();
    }

    public void setNum(String num) {
        this.num.set(num);
    }

    @Column(name = "name")
    public String getName() {
        return this.name.get();
    }

    public void setName(String name) {
        this.name.set(name);
    }

    //@Temporal(TemporalType.DATE)
    @Column(name = "due_date", length = 10)
    public Date getDueDate() {
        return Date.valueOf(this.dueDate.get());
    }

    public void setDueDate(Date dueDate) {
        this.dueDate.set(dueDate.toLocalDate());
    }

    @Column(name = "note")
    public String getNote() {
        return this.note.get();
    }

    public void setNote(String note) {
        this.note.set(note);
    }

//    @Column(name = "state")
//    public String getState() {
//        return this.state.get();
//    }
//
//    public void setState(String state) {
//        this.state.set(state);
//    }

}
