package app.item;
// Generated Feb 24, 2016 10:44:15 PM by Hibernate Tools 4.3.1


import app.supplier.Supplier;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemSupplier generated by hbm2java
 */
@Entity
@Table(name="item_supplier"
    ,catalog="sm"
)
public class ItemSupplier  implements java.io.Serializable {


     private ItemSupplierId id;
     private Item item;
     private Supplier supplier;
     private Integer quantity;

    public ItemSupplier() {
    }

	
    public ItemSupplier(ItemSupplierId id, Item item, Supplier supplier) {
        this.id = id;
        this.item = item;
        this.supplier = supplier;
    }
    public ItemSupplier(ItemSupplierId id, Item item, Supplier supplier, Integer quantity) {
       this.id = id;
       this.item = item;
       this.supplier = supplier;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idSupplier", column=@Column(name="id_supplier", nullable=false) ), 
        @AttributeOverride(name="idItem", column=@Column(name="id_item", nullable=false) ) } )
    public ItemSupplierId getId() {
        return this.id;
    }
    
    public void setId(ItemSupplierId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_item", nullable=false, insertable=false, updatable=false)
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_supplier", nullable=false, insertable=false, updatable=false)
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }




}


