package app.region;
import app.city.City;
import javafx.beans.property.StringProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.SimpleLongProperty;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name="region"
    ,catalog="sm"
)
public class Region  implements java.io.Serializable {


     private LongProperty idRegion;
     private StringProperty name;
     private Set<City> cities = new HashSet<City>(0);

    public Region() {
this.idRegion = new SimpleLongProperty();
this.name = new SimpleStringProperty();
}
public LongProperty idRegionProperty() {
        return idRegion;
    }
public StringProperty nameProperty() {
        return name;
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_region", unique=true, nullable=false)
    public Long getIdRegion() {
        return this.idRegion.get();
    }
    
    public void setIdRegion(Long idRegion) {
        this.idRegion.set(idRegion);
    }

    
    @Column(name="name")
    public String getName() {
        return this.name.get();
    }
    
    public void setName(String name) {
        this.name.set(name);
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="region")
    public Set<City> getCities() {
        return this.cities;
    }
    
    public void setCities(Set<City> cities) {
        this.cities = cities;
    }

    @Override
    public String toString() {
        return getName();
    }


}


