package app.supplier;

import app.orderline.Orderline;
import app.item.ItemSupplier;
import javafx.beans.property.StringProperty;
import javafx.beans.property.LongProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.SimpleLongProperty;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "sm"
)
public class Supplier implements java.io.Serializable {

    private LongProperty idSupplier;
    private StringProperty name;
    private StringProperty itemType;
    private StringProperty adresse;
    private StringProperty email;
    private StringProperty phone;
    private StringProperty fax;
    private Set<Orderline> orderlines = new HashSet<Orderline>(0);
    private Set<ItemSupplier> itemSuppliers = new HashSet<ItemSupplier>(0);

    public Supplier() {
        this.idSupplier = new SimpleLongProperty();
        this.name = new SimpleStringProperty();
        this.itemType = new SimpleStringProperty();
        this.adresse = new SimpleStringProperty();
        this.email = new SimpleStringProperty();
        this.phone = new SimpleStringProperty();
        this.fax = new SimpleStringProperty();
    }

    public LongProperty idSupplierProperty() {
        return idSupplier;
    }

    public StringProperty nameProperty() {
        return name;
    }

    public StringProperty itemTypeProperty() {
        return itemType;
    }

    public StringProperty adresseProperty() {
        return adresse;
    }

    public StringProperty emailProperty() {
        return email;
    }

    public StringProperty phoneProperty() {
        return phone;
    }

    public StringProperty faxProperty() {
        return fax;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_supplier", unique = true, nullable = false)
    public Long getIdSupplier() {
        return this.idSupplier.get();
    }

    public void setIdSupplier(Long idSupplier) {
        this.idSupplier.set(idSupplier);
    }

    @Column(name = "name")
    public String getName() {
        return this.name.get();
    }

    public void setName(String name) {
        this.name.set(name);
    }

    @Column(name = "item_type")
    public String getItemType() {
        return this.itemType.get();
    }

    public void setItemType(String itemType) {
        this.itemType.set(itemType);
    }

    @Column(name = "adresse")
    public String getAdresse() {
        return this.adresse.get();
    }

    public void setAdresse(String adresse) {
        this.adresse.set(adresse);
    }

    @Column(name = "email")
    public String getEmail() {
        return this.email.get();
    }

    public void setEmail(String email) {
        this.email.set(email);
    }

    @Column(name = "phone")
    public String getPhone() {
        return this.phone.get();
    }

    public void setPhone(String phone) {
        this.phone.set(phone);
    }

    @Column(name = "fax")
    public String getFax() {
        return this.fax.get();
    }

    public void setFax(String fax) {
        this.fax.set(fax);
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
    public Set<Orderline> getOrderlines() {
        return this.orderlines;
    }

    public void setOrderlines(Set<Orderline> orderlines) {
        this.orderlines = orderlines;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
    public Set<ItemSupplier> getItemSuppliers() {
        return this.itemSuppliers;
    }

    public void setItemSuppliers(Set<ItemSupplier> itemSuppliers) {
        this.itemSuppliers = itemSuppliers;
    }

    @Override
    public String toString() {
        return  getName() + " | " + getPhone() ;
    }

}
