package app.cash;

import app.payment.Payment;
import javafx.beans.property.FloatProperty;
import javafx.beans.property.SimpleFloatProperty;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Cash generated by hbm2java
 */
@Entity
@Table(name = "cash", catalog = "sm"
)
@PrimaryKeyJoinColumn(name="id_payment")  

public class Cash extends Payment implements java.io.Serializable {

    private FloatProperty cashTendered;

    public Cash() {
        this.cashTendered = new SimpleFloatProperty();
    }

    public FloatProperty cashTenderedProperty() {
        return cashTendered;
    }

    @Column(name = "cash_tendered", precision = 12, scale = 0)
    public Float getCashTendered() {
        return this.cashTendered.get();
    }

    public void setCashTendered(Float cashTendered) {
        this.cashTendered.set(cashTendered);
    }

}
